import subprocess
import os
import sys

def run_cmd(args):
    print(f"Running: {' '.join(args)}")
    res = subprocess.run(args, check=False)
    if res.returncode != 0:
        print(f"❌ Command failed: {' '.join(args)}")
        sys.exit(res.returncode)

def main():
    print("🚀 Initializing Python Project Environment using uv...")
    
    # 1. Initialize venv
    if not os.path.exists(".venv"):
        run_cmd(["uv", "venv"])
    else:
        print("ℹ️  .venv already exists. Skipping creation.")
        
    # 2. Add dependencies
    run_cmd(["uv", "add", "--dev", "ruff", "pytest"])
    
    # 3. Create a default pyproject.toml if missing
    if not os.path.exists("pyproject.toml"):
        print("Creating default pyproject.toml with strict Ruff rules...")
        toml_content = """[project]
name = "python-project"
version = "0.1.0"
description = "Autogenerated python project"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[tool.ruff]
line-length = 88
target-version = "py310"

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "UP",  # pyupgrade
    "SIM", # flake8-simplify
]
ignore = []

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
"""
        with open("pyproject.toml", "w") as f:
            f.write(toml_content)
        print("✅ pyproject.toml created successfully.")
    else:
        print("ℹ️  pyproject.toml already exists. Skipping creation.")
        
    # 4. Create dummy test structure
    os.makedirs("tests", exist_ok=True)
    test_file = os.path.join("tests", "test_sanity.py")
    if not os.path.exists(test_file):
        with open(test_file, "w") as f:
            f.write("""def test_sanity():
    assert True
""")
        print("✅ Created tests/test_sanity.py sanity test.")
        
    print("\n🎉 Environment bootstrapping completed successfully!")
    print("Run `uv run ruff check` and `uv run pytest` to verify.")

if __name__ == "__main__":
    main()
